services:
  backend:
    image: capstoneacr.azurecr.io/backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env.prod
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - migration

  frontend:
    image: capstoneacr.azurecr.io/frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - .env.prod
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  # migration:
  #   image: capstoneacr.azurecr.io/backend:latest
  #   container_name: migration
  #   env_file:
  #     - .env.prod
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}

migration:
  image: capstoneacr.azurecr.io/migration:latest
  container_name: migration
  env_file:
    - /env.prod
  environment:
    - DATABASE_URL=${DATABASE_URL}
    - POSTGRES_HOST=${POSTGRES_HOST}
    - POSTGRES_PORT=${POSTGRES_PORT}
  depends_on:
    - backend

volumes:
  pgdata: